#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Remove the interactive prompt for rm set by Prezto by default
unalias rm

# Docker Compose Aliases
alias dc="docker-compose"
# Stop all containers
alias dstop='docker stop $(docker ps -a -q)'
# Remove all containers
alias drm='docker rm $(docker ps -a -q)'
# Stop and remove all containers
alias drmf='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'
# Remove all images
alias dri='docker rmi $(docker images -q)'
# Processes
alias dps='docker ps'
alias dpsa='docker ps -a'
# Remove orphaned volumes
alias dclean='docker volume rm $(docker volume ls -qf dangling=true)'
# Show all aliases related to docker
dalias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }

alias git-clean-merged='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d'
